<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\jaytwo.DataExport.Csv\jaytwo.DataExport.Csv.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="LumenWorksCsvReader" Version="4.0.0" />
  </ItemGroup>
</Project>
